# Generated by Django 4.0.4 on 2022-06-09 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
