# Generated by Django 3.2.13 on 2022-06-18 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo del Usuario')),
                ('user_name', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('profile_pic', models.ImageField(default='fotoPerfiles/default.jpg', upload_to='fotoPerfiles/', verbose_name='Foto del Usuario')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Status')),
                ('nombre', models.CharField(max_length=30, verbose_name='Tipo de status')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo rol')),
                ('nombreRol', models.CharField(max_length=30, verbose_name='Nombre rol')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Tipo')),
                ('nombreTipo', models.CharField(max_length=30, verbose_name='Nombre del Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Post')),
                ('fechaPost', models.DateField(verbose_name='Fecha del Post')),
                ('tituloPost', models.CharField(max_length=150, verbose_name='Titulo del Post')),
                ('descPost', models.CharField(max_length=500, verbose_name='Descripcion del Post')),
                ('imagenPost', models.ImageField(blank=True, null=True, upload_to='imagenPosts')),
                ('razonPost', models.CharField(max_length=100, null=True, verbose_name='Razon del Baneo')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakaNeko.estado')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakaNeko.tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idCom', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Comentario')),
                ('fechaCom', models.DateField(verbose_name='Fecha del comentario')),
                ('razonCom', models.CharField(max_length=100, null=True, verbose_name='Razon del Baneo')),
                ('descCom', models.CharField(max_length=400, verbose_name='Contenido del comentario')),
                ('estado', models.ForeignKey(default='Activo', on_delete=django.db.models.deletion.SET_DEFAULT, to='bakaNeko.estado')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakaNeko.post')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='bakaNeko.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
