# Generated by Django 4.0.4 on 2022-05-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Usuario')),
                ('nombreUsuario', models.CharField(max_length=30, verbose_name='Nombre de Usuario')),
                ('contrasenia', models.CharField(max_length=20, verbose_name='Contraseña del Usuario')),
                ('email', models.EmailField(max_length=30, verbose_name='Correo del Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(null=True, upload_to='fotoPerfiles')),
                ('pais_perfil', models.CharField(max_length=20, verbose_name='Pais del Usuario')),
                ('tipo_user', models.CharField(max_length=5, verbose_name='Tipo de Usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakaNeko.usuario')),
            ],
        ),
    ]
