# Generated by Django 2.2.28 on 2022-05-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakaNeko', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
