# Generated by Django 2.2.28 on 2022-05-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakaNeko', '0002_auto_20220525_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Status')),
                ('nombre', models.CharField(max_length=30, verbose_name='Tipo de status')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo rol')),
                ('nombreRol', models.CharField(max_length=30, verbose_name='Nombre rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Usuario')),
                ('nombreUsuario', models.CharField(max_length=30, verbose_name='Nombre de Usuario')),
                ('contrasenia', models.CharField(max_length=20, verbose_name='Contraseña del Usuario')),
                ('email', models.EmailField(max_length=30, verbose_name='Correo del Usuario')),
                ('fotoUsuario', models.ImageField(null=True, upload_to='fotoPerfiles')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakaNeko.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Post')),
                ('fechaPost', models.DateField(verbose_name='Fecha del Post')),
                ('tituloPost', models.CharField(max_length=150, verbose_name='Titulo del Post')),
                ('descPost', models.CharField(max_length=500, verbose_name='Descripcion del Post')),
                ('imagenPost', models.ImageField(null=True, upload_to='imagenPosts')),
                ('razonPost', models.CharField(max_length=100, null=True, verbose_name='Razon del Baneo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakaNeko.Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakaNeko.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idCom', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Comentario')),
                ('fechaCom', models.DateField(verbose_name='Fecha del comentario')),
                ('razonCom', models.CharField(max_length=100, null=True, verbose_name='Razon del Baneo')),
                ('descCom', models.CharField(max_length=400, verbose_name='Contenido del comentario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakaNeko.Estado')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakaNeko.Post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakaNeko.Usuario')),
            ],
        ),
    ]
