# Generated by Django 3.2.13 on 2022-07-07 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakaNeko', '0002_auto_20220707_2331'),
    ]

    operations = [
    ]
